name: 'Add a changeset for dependency updates'
description: ''
author: 'Matthew Scharley'

# Define your inputs here.
inputs:
  changeset-folder:
    description: 'Which folder to store your changesets in'
    required: false
    default: '.changeset'
  token:
    description: 'A Github access token used to push commits back to the PR'
    required: false
  use-semantic-commits:
    description: 'Whether to respect semantic commit prefixes'
    required: false
    default: 'true'
  commit-message:
    description: 'The message to use for commits'
    required: false
    default: 'chore(deps): changeset for dependency update'
  author-name:
    description: 'The name of the author to use when committing'
    required: false
  author-email:
    description: 'The email for the author to use when committing'
    required: false

# Define your outputs here.
outputs:
  created-changeset:
    description: 'Whether a new changeset was created or not'

runs:
  using: node20
  main: dist/index.js
