name: 'Add a changeset for dependency updates'
description: "Github Action to publish changesets to dependency update PR's"
branding:
  icon: package
  color: purple
author: 'Matthew Scharley'

# Define your inputs here.
inputs:
  changeset-folder:
    description: 'Which folder to store your changesets in'
    required: false
    default: '.changeset'
  token:
    description: 'A Github access token used to push commits back to the PR'
    required: false
  use-semantic-commits:
    description: 'Deprecated: use use-conventional-commits instead'
    deprecationMessage: 'Renamed to `use-conventional-commits`.'
    required: false
  use-conventional-commits:
    description: 'Whether to respect conventional commit prefixes'
    required: false
    default: 'true'
  commit-message:
    description: 'The message to use for commits'
    required: false
    default: 'chore(deps): changeset for dependency update'
  author-name:
    description: 'The name of the author to use when committing'
    required: false
  author-email:
    description: 'The email for the author to use when committing'
    required: false
  author-dco:
    description: 'Whether a custom author should sign off using DCO'
    required: false
    default: 'false'
  sign-commits:
    description: 'Generate signed commits. This uses a different Github API which conflicts with custom author information.'
    required: false
    default: 'false'

# Define your outputs here.
outputs:
  created-changeset:
    description: 'Whether a new changeset was created or not'

runs:
  using: node20
  main: dist/index.js
